Add Qt6 android support and QtQuick client example
frankosterfeld/qtkeychain pull request #196
Opened 2021-07-22 07:51 UTC by freedbrt

2021-10-05 08:30 UTC, frankosterfeld commented on TestAppExample/.gitignore
> +# This file is used to ignore files which are generated
I think this could be merged into the top-level .gitignore?

2021-10-05 08:38 UTC, frankosterfeld requested changes

2021-10-05 08:38 UTC, frankosterfeld commented on TestAppExample/keychainclass.cpp
> +            emit error(QString("Write key failed: %1").arg(qPrintable(m_readCredentialJob.errorString())));
"Write key failed" should read "Read key failed". Also use QStringLiteral() or maybe better, tr() (although nobody will ever translate this test app, I guess)

2021-10-05 08:40 UTC, frankosterfeld reviewed
Android/Qt6 support patch looks good!

2021-10-05 09:31 UTC, frankosterfeld commented on TestAppExample/TestAppExample.pro
> +include(../qt5keychain.pri)
in current master, this file is now renamed to qtkeychain.pri

2021-10-05 10:55 UTC, freedbrt commented
Ok, done

2022-09-14 10:52 UTC, PeterPetrik commented
We are migrating merginmaps.com to Qt6, this patch is critical so we can build Android. Would it be possible to merge it and create new qtkeychain release?

2022-09-14 11:03 UTC, PeterPetrik commented
This needs a change, https://github.com/frankosterfeld/qtkeychain/blob/f197cdb935b0cfd9881fdc6860874cb8379d1238/CMakeLists.txt#L98 should be removed, there is no Qt6AndroidExtras package at all.

2022-09-14 11:04 UTC, PeterPetrik commented
@frankosterfeld shall we fix this PR, or shall I create a simpler PR with just a required changes?

2022-09-14 11:06 UTC, frankosterfeld commented
I'd say fix up this PR. I hope i get to a new release when back from vacation.

2022-09-14 11:13 UTC, PeterPetrik commented
@frankosterfeld cannot modify his branch, maybe the stuff can be removed after mergin it?

here is the patch
```
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -91,11 +91,11 @@ else()
   find_package(Qt6 COMPONENTS Core REQUIRED)
   set(QTKEYCHAIN_VERSION_INFIX 6)
 
-  if(ANDROID)
-    find_package(Qt6 COMPONENTS AndroidExtras REQUIRED)
-    include_directories(${Qt6AndroidExtras_INCLUDE_DIRS})
-    set(QTANDROIDEXTRAS_LIBRARIES ${Qt6AndroidExtras_LIBRARIES})
-  endif()
+  # if(ANDROID)
+  #  find_package(Qt6 COMPONENTS AndroidExtras REQUIRED)
+  #  include_directories(${Qt6AndroidExtras_INCLUDE_DIRS})
+  #  set(QTANDROIDEXTRAS_LIBRARIES ${Qt6AndroidExtras_LIBRARIES})
+  # endif()
 
   if(UNIX AND NOT APPLE AND NOT ANDROID AND NOT HAIKU)
     find_package(Qt6 COMPONENTS DBus REQUIRED)
```

2022-09-14 11:15 UTC, freedbrt commented
@PeterPetrik i can modify, if it needed

2022-09-14 11:16 UTC, PeterPetrik commented
@freedbrt thanks!

2022-09-28 10:11 UTC, merged

2022-09-28 10:11 UTC, frankosterfeld commented
Thanks!

2022-09-28 10:52 UTC, michaelk83 commented
> I hope i get to a new release when back from vacation.

@frankosterfeld , if you're preparing a new release, would it be possible to also include #75 ? It needs an update, but it's a small change, so shouldn't be too complicated...